### ISSUE TITLE
Running feet spilling over onto a second line

### ISSUE THREAD

**Issue by tw77** [pressbooks/pressbooks-book#986] opened 2022-03-01 21:49 UTC
### Description

On PDF exports, running feet over a certain length (around ~30 characters) appear on two lines instead of one. This only happens on the first page of a chapter. This was reported and observed with Jacobs, but it affects McLuhan too.

<img width="347" alt="Screen Shot 2022-03-01 at 1 44 50 PM" src="https://user-images.githubusercontent.com/44182629/156254118-8282cb68-adb5-41a0-bdde-cc9de42e25d5.png">
<img width="534" alt="Screen Shot 2022-03-01 at 1 44 58 PM" src="https://user-images.githubusercontent.com/44182629/156254132-b31a8172-a56d-4ec2-813c-9485e5c82e2a.png">

### Steps to Reproduce

1. Create a book and set the theme to McLuhan or Jacobs.
2. Add a chapter with a fairly long (>30 character) title.
3. Add enough content to the chapter to make it longer than a single page in an exported PDF.
4. Export a PDF.

**Expected behavior:** Running feet (set by default to chapter title) = one line only.

**Actual behavior:** Running feet = two lines on the first page of the chapter, one line on subsequent pages.

**Comment by SteelWagstaff** [comment] 2022-03-02 15:40
Questions:
1. is the behaviour the same for recto & verso pages? _Yes_
2. what happens when chapter becomes too long to safely print on a single page in ANY case?
3. can we find any similar issues in prince forum

**Comment by tw77** [comment] 2022-03-04 18:30
When the chapter becomes too long to safely print on a single page in any case, we see similar behaviour:

on the **opening page** of a chapter, running feet = two lines, with the threshold for the first line appearing to be ~35 characters. The second line continues for another ~35 characters max. The cutoff always happens at the end of a word, not in the middle of a word. The total character count included in my (McLuhan) example here is 67:

<img width="459" alt="Screen Shot 2022-03-04 at 10 12 44 AM" src="https://user-images.githubusercontent.com/44182629/156818847-03c21274-2e3f-4fc8-8ff4-34295230a309.png">

on **subsequent pages** in a chapter, running feet = two lines, with seemingly double the threshold for included characters (character count here is 135):

<img width="904" alt="Screen Shot 2022-03-04 at 10 13 36 AM" src="https://user-images.githubusercontent.com/44182629/156818965-5fad1b6c-2ff5-4bd9-816f-4f5eaf3d59b0.png">

Curiously, for too-long chapter titles, the page number disappears on recto pages but appears on verso pages. This is true regardless of whether the page is an opening page for a chapter or a subsequent page:

<img width="463" alt="Screen Shot 2022-03-04 at 10 29 05 AM" src="https://user-images.githubusercontent.com/44182629/156821062-1e5185e9-cfd0-4806-bdb8-fc97a4bd25fd.png">
<img width="897" alt="Screen Shot 2022-03-04 at 10 29 28 AM" src="https://user-images.githubusercontent.com/44182629/156821107-2fd63ee2-bbff-4bdd-a3b9-349f14080377.png">

That being said, there are no observable differences between recto and verso pages with chapter titles that are _not_ too long to print in full.

I haven't been able to find similar issues in prince forum.

**Comment by tw77** [comment] 2022-12-21 15:03
This came up for a different user (https://pressbooks.zendesk.com/agent/tickets/13657 for internal reference) using Christie theme and trying McLuhan too. Running feet have a different wrap length on the first pages of chapters and Parts vs. in other pages in a PDF export.

In this case, a workaround is omitting running content from the first page of each chapter or Part. This can be done using a PDF editor to construct a final PDF from two export files (one with running content and one without) or possibly by using CSS.

If an author wants to include running content on every page, in a theme where running content appears in running feet, I don't know of a workaround that allows for exporting the running feet with the same wrap length throughout the book.

**Comment by SteelWagstaff** [comment] 2022-12-22 17:11
Talked with @greatislander about this. This is being caused by a mixin that sets content to blank for every page position on the first page of content. He'll add some notes.

**Comment by greatislander** [comment] 2022-12-23 02:55
Basically what appears to be happening is this:

A book theme might show running content at the top outside of a page except on the first page of a chapter. This would be achieved with the following CSS:

```css
@page chapter:left {
	@top-left {
		content: "My Running Content";
	}
}

@page chapter:right {
	@top-right {
		content: "My Running Content";
	}
}
```

So far so good. However, the first page a chapter will have this running content in the top left or right (depending on recto-verso rules) so we need override it like this:

```css
@page:chapter:first {
	@top-right {
		content: '';
	}

	@top-left {
		content: '';
	}
}
```

Then we can explicitly add rules after the blank reset to show whatever content we want on the first page (which will usually be different and usually is only in the footer, but varies from theme to theme.

Here's the code in Buckram that does this: https://github.com/pressbooks/buckram/blob/27504fc3322278b33ea751772f282bfeda34a5ff/assets/styles/components/structure/_blank.scss#L11-L86

But, there's a problem. Because are setting all these areas to have a blank string as content, it appears that we're preventing any overflow into other areas.

So for this issue, the content is set to appear in `@bottom-right` but unlike other pages in the chapter, it is constrained to `@bottom-right` because `@bottom-center` already has content (a blank string).

I think the fix for this is quite straightforward, though. Rather then setting content to `''` I think the `blank` mixins can be updated to use `content: unset` (the `unset` keyword basically tells the rendering engine to remove any styles that have been applied to this property). So instead of the `@bottom-center` having a blank string it would have nothing and the layout would work as expected. I'm opening a Buckram PR for this— you can test it in McLuhan by copying the `_blank.scss` file from my Buckram PR into [`packages/buckram/assets/styles/components/structure/`](../tree/dev/packages/buckram/assets/styles/components/structure).

**Closed** 2023-01-03 19:31 UTC
Labels: bug
