### ISSUE TITLE
Footnotes inside Part text not converted to Endnotes (PDF)

### ISSUE THREAD

**Issue by alexdryden** [pressbooks/pressbooks-book#610] opened 2019-10-23 16:03 UTC
### Description

Footnotes from Part text are not converted to endnotes in pdf text and pdf digital.  (However, they do show up as regular footnotes if that option is selected).

### Steps to Reproduce

1. Add text that contains a footnote to a Part (e.g., to "Main Body" default part):

<img width="1390" alt="Screen Shot 2019-10-23 at 11 53 38 AM" src="https://user-images.githubusercontent.com/47127862/67411657-f8816680-f58b-11e9-8ca9-f8b0584c618b.png">

2. In Appearance > Theme Options > PDF Options > Footnote Style, select radio for 'Display as chapter endnotes' and save.
3. Export to pdf text and pdf digital.

**Expected behavior:** 
After the Part's text, the footnotes appear under a 'Notes' heading. (Same behavior as chapter endnotes).

**Actual behavior:** 
Footnotes and 'Notes' heading are missing after the Part's text

#### Book Info

Book ID: 15
Book URL: https://pww-dev.library.illinois.edu/wordpress/endnotes/
Book Privacy: Public

#### Browser

Platform: OS X
Browser Name: Safari
Browser Version: 13.0.2
User Agent String: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.2 Safari/605.1.15

#### WordPress Configuration

Network URL: http://pww-dev.library.illinois.edu/wordpress/
Network Type: Subdirectory
Version: 5.2.3
Language: en_US
WP_ENV: Not set
WP_DEBUG: Disabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.9.2
Book Theme: McLuhan
Book Theme Version: 2.8.10
Root Theme: Pressbooks Publisher
Root Theme Version: 3.1.4

#### Pressbooks Dependencies

Epubcheck: Not Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Not Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

Pressbooks: 5.9.2

#### Book Active Plugins

Pressbooks: 5.9.2

#### Inactive Plugins

Akismet Anti-Spam: 4.1.1
Hello Dolly: 1.6

#### Server Configuration

PHP Version: 7.2.23
MySQL Version: 5.5.5
Webserver Info: Apache/2.4.6 (Red Hat Enterprise Linux) OpenSSL/1.0.2k-fips PHP/7.2.23

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 256M
Upload Max Size: 8M
Post Max Size: 8M
Upload Max Filesize: 8M
Time Limit: 30
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Zend
XDebug: Disabled
cURL: Supported
cURL Version: 7.29.0
imagick: Not Installed
xsl: Installed

**Comment by SteelWagstaff** [comment] 2019-11-29 18:45
Thanks for reporting @alexdryden -- we're looking into this and hope to fix this in a future release!

**Comment by mcgratay** [comment] 2020-01-09 18:54
Confirmed as reproducible. 

Example: https://partswithoutendnotes.textopress.com/
PDF file: [Parts-Without-Endnotes-1578595912._print.pdf](https://github.com/pressbooks/pressbooks-book/files/4041987/Parts-Without-Endnotes-1578595912._print.pdf)

**Comment by ricardopressbooks** [comment] 2020-04-16 14:40
It was fixed in presbook plugin branch **pb-290-footnotes-issues**

**Comment by SteelWagstaff** [comment] 2020-04-24 01:34
Tested on integrations. Works as intended. Ready for release.

**Closed by SteelWagstaff** 2020-04-24 01:34 UTC
Labels: Small - 3, bug, export formats
