### ISSUE TITLE
Only Super Admins able to embed IFrame from My Open Math Lab (https://www.myopenmath.com/) 

### ISSUE THREAD

**Issue by JoshHCC** [pressbooks/pressbooks-book#1137] opened 2022-12-01 21:28 UTC
Only our Super Admins are able to embed iframes from My Open Math. We have whitelisted myopenmath.com. under sharing and privacy for our Pressbooks network. Has anyone else had success with the whitelisting of sites? Do you have any other suggestions for us?

Example Embed Code for problem:
https://www.myopenmath.com/embedq2.php?id=110368

### Steps to Reproduce

1.  Log in as a non super admin
2.  Go to the text editor and paste embed/iframe code: 
<code><iframe src=https://www.myopenmath.com/embedq2.php?id=110368 width="600" height="350"</iframe></code>
3.  click visual and it looks fine (problem is embedded), click save and you get "Failed to Embed"
4. Return to page and click the text editor on Text, extra embed brackets added to original code pasted and it doesn't display using view chapter or preview.

<code></code>

[embed]https://www.myopenmath.com/embedq2.php?id=110368[/embed]

<code></code>

### Prerequisites

* [ ] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [ ] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [McLuhan](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [ ] Are you experiencing the issue while using this book theme?
* [ ] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

**Expected behavior:** 

**Actual behavior:**

**Comment by SteelWagstaff** [comment] 2022-12-01 21:41
@JoshHCC closing -- this is not a bug. I was able to embed as expected, as seen in this chapter: https://integrations.pressbooks.network/ricksbook/chapter/chapter-1/

Be sure that you 
1. add `www.myopenmath.com` to your allowlist and 
2. enter the iframe like this: `<iframe src="https://www.myopenmath.com/embedq2.php?id=110368" width="600" height="350"</iframe>` and it should work for you as a regular user.

The path was missing `www` in the allowlist and the iframe didn't have `"` arounds the src attribute. I think both of those were contributing to your problem. 

In the future -- try posting in the community forum (https://pressbooks.community/) for issues like this?

**Closed as completed by SteelWagstaff** 2022-12-01 21:41 UTC

**Comment by JoshHCC** [comment] 2022-12-01 22:39
Steel,
Thank you so much. We have been working on this for days. We appreciate your expert guidance. I was able to apply your fix successfully.



________________________________
