### ISSUE TITLE
Inconsistent line spacing in table cells that contain more than one paragraph (Web book)

### ISSUE THREAD

**Issue by josieg** [pressbooks/pressbooks-book#242] opened 2018-07-27 17:32 UTC
### Prerequisites

* Pressbooks 5.4.0
* [x] Are you experiencing the issue while using this book theme?
* [x] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description
In the web book, table cells that contain more than one paragraph have inconsistent line spacing. The first paragraph in each cell will have no extra space between lines. All additional paragraphs in the same cell will have extra space between the lines. This applies to both data cells and headers cells. 

I have tested this on a few different browsers and with different themes and this behavior is consistent. This only seems to affect the web book (The visual-editor view, PDF, and ODT files were fine).

Here is an example: https://pressbooks.bccampus.ca/abookfortestingprod/chapter/chapter-1/

### Steps to Reproduce

1. Create a table in Pressbooks with any theme. 
2. Add two paragraphs within one table cell.
3. Save the page.
4. View the page in the web book.
5. See the inconsistent spacing. 

**Expected behavior:**
I expect that the line spacing in tables is consistent when adding multiple paragraphs in one table cell. 

**Actual behavior:**

#### Book Info

Book ID: 500
Book URL: https://pressbooks.bccampus.ca/abookfortestingprod/
Book Privacy: Public

#### Browser

Platform: Windows
Browser Name: Chrome (I also tested Firefox and Edge - same behaviour)
Browser Version: 67.0.3396.99
User Agent String: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.99 Safari/537.36

#### WordPress Configuration

Network URL: http://pressbooks.bccampus.ca/
Network Type: Subdirectory
Version: 4.9.7
Language: en_US
WP_ENV: Not set
WP_DEBUG: Enabled
Memory Limit: 64M

#### Pressbooks Configuration

Version: 5.4.0
Book Theme: Open Textbooks
Book Theme Version: 2.1.4
Root Theme: Aldine
Root Theme Version: 1.4.0

#### Pressbooks Dependencies

Epubcheck: Installed
Kindlegen: Installed
xmllint: Installed
PrinceXML: Installed
Saxon-HE: Installed

#### Must-Use Plugins

hm-autoloader.php: n/a

#### Network Active Plugins

BC Post-Secondary Validator: 1.0.0
CC Export for Pressbooks: 0.2.3
f5 Force SSL: 1.0.0
iThemes Security: 7.0.4
Openstax Import for Pressbooks: 1.2.2
Pressbooks: 5.4.0
Pressbooks Stats: 1.4.0
Textbooks for Pressbooks: 4.1.2
WP-Piwik: 1.0.19

#### Book Active Plugins

H5P: 1.10.3

#### Inactive Plugins

Akismet Anti-Spam: 4.0.8
Candela Citation: 0.2.2
mPDF for Pressbooks: 3.2.0
WP QuickLaTeX: 3.8.4

#### Server Configuration

PHP Version: 7.1.19
MySQL Version: 5.5.5
Webserver Info: Apache

#### PHP Configuration

Safe Mode: Disabled
Memory Limit: 512M
Upload Max Size: 500M
Post Max Size: 500M
Upload Max Filesize: 500M
Time Limit: 60
Max Input Vars: 1000
URL-aware fopen: On (1)
Display Errors: N/A

#### PHP Extensions

OPcache: Disabled
XDebug: Disabled
cURL: Supported
cURL Version: 7.19.7
imagick: Installed
xsl: Installed

**Comment by greatislander** [comment] 2018-07-30 11:29
Thanks for this @josieg — does this issue occur in EPUB/MOBI as well? If you haven't tested, no worries. I just note from your issue description that you don't mention those formats.

**Comment by josieg** [comment] 2018-07-30 15:18
Hi @greatislander! No, I didn't check the ebook formats.

**Comment by greatislander** [comment] 2018-12-03 21:18
@josieg Looking at the HTML in your example chapter, I see:

```html
<td>Hello, world. This is text. More text. Text, text, text, so much text. Now to copy and paste more text.<p></p>
<p>Hello, world. This is text. More text. Text, text, text, so much text. Now to copy and paste more text.</p>
<p>Hello, world. This is text. More text. Text, text, text, so much text. Now to copy and paste more text.</p></td>
```

Note that for some reason the first paragraph is NOT contained in `<p>` tags. Can you add them manually? Does that fix the issue?

**Comment by josieg** [comment] 2018-12-03 22:37
Hi Ned. When I look in the Text Editor, there are no p tags:
![html](https://user-images.githubusercontent.com/23706762/49405808-79cbd280-f708-11e8-984b-ff3d42275e91.JPG)

And when I try to add `<p>` tags, they are stripped out when I switch back to the html editor.

**Comment by greatislander** [comment] 2018-12-03 23:22
Thanks! This sounds like an issue with WordPress. I will investigate further.

**Comment by greatislander** [comment] 2018-12-04 02:30
Hi @josieg, confirmed -- this is a bug with WordPress (I tested on a vanilla, Pressbooks-free WordPress install and could reproduce the behaviour). For context, WordPress uses a PHP function called `wpautop()` to automatically add paragraphs. It looks like they way the content in the `<td>` tag is entered causes that function to behave in an unexpected way. I was able to get the paragraphs added properly by changing your example as follows:

```diff
- <td>Hello, world. This is text. More text. Text, text, text, so much text. Now to copy and paste more text.
+ <td>
+
+ Hello, world. This is text. More text. Text, text, text, so much text. Now to copy and paste more text.

Hello, world. This is text. More text. Text, text, text, so much text. Now to copy and paste more text.

Hello, world. This is text. More text. Text, text, text, so much text. Now to copy and paste more text.
</td>

Adding a blank line after the opening `<td>` seems to get WordPress's paragraph handling to work properly and should resolve the problem you are encountering for now. I know this isn't ideal, but it's my feeling that this should be fixed in WordPress Core so I'm going to open a ticket there. Thanks again for reporting this issue!

**Closed by greatislander** 2018-12-04 02:30 UTC
Labels: bug, wontfix

**Comment by josieg** [comment] 2018-12-04 16:11
Thanks, Ned! This is helpful.
