### ISSUE TITLE
'Float' is not respected in a left- or right-aligned image in PDF export without a caption

### ISSUE THREAD

**Issue by pb-amy** [pressbooks/pressbooks-book#724] opened 2020-09-03 21:03 UTC
### Prerequisites

* [X] Can you reproduce the behavior you wish to address with [all plugins except Pressbooks deactivated](http://codex.wordpress.org/Multisite_Network_Administration#Plugins)?
* [X] Are you running the [latest version of Pressbooks](http://github.com/pressbooks/pressbooks/releases/latest/), the latest version of [McLuhan](http://github.com/pressbooks/pressbooks-book/releases/latest/), and the [latest version of WordPress](http://codex.wordpress.org/Upgrading_WordPress)?
* [X] Are you experiencing the issue while using this book theme?
* [X] Did you [perform a cursory search](https://github.com/issues?q=+is%3Aissue+repo%3Apressbooks%2Fpressbooks-book) to see if your bug or enhancement is already listed?

### Description

Internal note: This bug was brought to attention as [this ticket in Zendesk](https://pressbooks.zendesk.com/agent/tickets/1908).

Two important notes: This is happening across all themes, and this is only happening in PDF.

When an image is aligned left or aligned right AND image does not have a caption, the `float` function is not respected. The text next to the image will not float along the side of the image, but will instead be pushed to the bottom of the image. The `float` function is respected when the image has a caption.

![Screen Shot 2020-09-03 at 5 02 14 PM](https://user-images.githubusercontent.com/61845107/92166794-3899b280-ee07-11ea-9101-978c7f50b974.png)

Right now, the following CSS works, but we should aim to have this fixed:
```
img.alignleft{
  float: left;
}
```
```
img.alignright{
  float: right;
}
```

### Steps to Reproduce

1. Place an image and align it left or right
2. Put in text next to the image
3. Observe that the float function is respected in epub and web but not PDF.

**Expected behavior:** Float function should be respected in PDF whether or not there is a caption on the image.

**Actual behavior:** Float function is not respected in PDF when there isn't a caption on the image, and the text gets pushed to the bottom of the image.

**Comment by SteelWagstaff** [comment] 2020-09-03 22:29
Closing as duplicate of https://github.com/pressbooks/pressbooks/issues/1741

**Closed by SteelWagstaff** 2020-09-03 22:29 UTC
