### ISSUE TITLE
Kindle image improvements

### ISSUE THREAD

**Issue by greatislander** [pressbooks/pressbooks-book#330] opened 2018-04-17 19:28 UTC
### MOBI

- [x] Align center
- [x] Align center, captioned
- [ ] Align left
- [x] Align left, captioned
- [ ] Align right
- [x] Align right, captioned
- [ ] Align none
- [ ] Align none, captioned

**Comment by mcgratay** [comment] 2020-02-04 16:01
Expected behavior is for left- or right-aligned images to resize to 50% of the page size no matter what size they are uploaded as originally. This is working as intended in all ebook formats, and explains some of the variations in size across differently aligned images in Kindle. 

However, images aligned "Center" or "None" do still show some unexpected size differences. Specifically, the captioned versions of these images become very small in comparison to uncaptioned originals. In the image below, an Align None image is on the left, and an Align None captioned images is on the right: 

![Screen Shot 2020-02-04 at 10 59 01 AM](https://user-images.githubusercontent.com/39064028/73761817-5b62cc00-473d-11ea-9c46-8cb178dc5f99.png)

A revised version of the above checklist would be: 

[x} Align center
[ ] Align center, captioned
[x] Align left
[x] Align left, captioned
[x] Align right
[x] Align right, captioned
[x] Align none
[ ] Align none, captioned

**Comment by SteelWagstaff** [comment] 2021-06-06 14:31
Wont fix

**Closed by SteelWagstaff** 2021-06-06 14:31 UTC
Labels: buckram, bug, enhancement, export formats, needs-reproduction
